Repository rubocop/rubocop, pull requests merged in 2021-02, with the labels that each got.

#9510 Fix typo in Style/DoubleNegation, nagation => negation
  lib/rubocop/cop/style/double_negation.rb
Labels: auto-merge

#9522 Fix typo in documentation syntax
  lib/rubocop/cop/lint/debugger.rb
Labels: documentation

#9528 Fixed typo in docs part 2
  docs/modules/ROOT/pages/cops_lint.adoc
Labels: auto-merge, documentation

#9542 Fix `Layout/FirstArgumentIndentation` for operator methods not called as operators.
  CHANGELOG.md
  changelog/fix_fix_layoutfirstargumentindentation_for.md
  lib/rubocop/cop/layout/first_argument_indentation.rb
  spec/rubocop/cop/layout/first_argument_indentation_spec.rb
Labels: auto-merge
